apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 3
  resources:
    requests:
      memory: 1Gi
  retention: 240h
  storage:
    volumeClaimTemplate:
      metadata:
        name: altermanager-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "alicloud-disk-ssd"
        resources:
          requests:
            storage: 20Gi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.18.0
