kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  namespace: monitoring
spec:
  storageClassName: "alicloud-disk-ssd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
